name: EmeraldCoreUI
main: EmeraldCoreUI\Main
api: [3.0.0, 3.1.0, 3.1.1, 3.1.4, 4.0.0]
version: 1.0
author: EmeraldMC
description: EmeraldCoreUI
commands:
 ecore:
  usage: /ecore
  description: Opens The EmeraldCoreUI Menu!
